Emilien/mlir xdsl
xdslproject/devito pull request #56
Opened 2024-02-14 17:39 UTC by PapyChacal

:warning: currently using a temporary xDSL branch, this actually depends on:
- xdslproject/xdsl#2161
- xdslproject/xdsl#2163
- xdslproject/xdsl#2164

Drive MLIR pipeline through xDSL to prepare for more back and forth.
Tested working and correct for GPU locally.

2024-02-20 16:49 UTC, georgebisbas commented on devito/core/cpu.py
> +                # mlir_cmd = f'mlir-opt -p {mlir_pipeline}'
Why would you prefer this separate?

2024-02-20 16:49 UTC, georgebisbas commented on devito/core/cpu.py
> +                # mlir_cmd = f'mlir-opt -p {mlir_pipeline}'
same

2024-02-21 13:27 UTC, georgebisbas approved these changes

2024-02-21 13:27 UTC, georgebisbas reviewed
flake8 needs some fixing

2024-02-21 13:29 UTC, georgebisbas requested changes
flake8

2024-02-21 13:31 UTC, PapyChacal commented
> flake8

:heavy_check_mark:

2024-02-21 13:35 UTC, merged